services:
  mqtt_broker:
    image: eclipse-mosquitto
    container_name: mqtt_mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./VolumesMosquitto/config:/mosquitto/config
      - ./VolumesMosquitto/data:/mosquitto/data
      - ./VolumesMosquitto/log:/mosquitto/log
  mqtt_clientweb:
    image: emqx/mqttx-web
    container_name: mqtt_mqttx-web
    ports:
      - "8082:80"  # Interface Web disponible sur localhost:3000
    depends_on:
      - mqtt_broker

